// <auto-generated />
using System;
using ControleFinanceiro.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ControleFinanceiro.Infra.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20201009213057_Update na tabela conta a pagar")]
    partial class Updatenatabelacontaapagar
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ControleFinanceiro.Domain.Models.ContaAPagar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnName("data_atualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriação")
                        .HasColumnName("data_criacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnName("data_pagamento")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnName("data_vencimento")
                        .HasColumnType("datetime");

                    b.Property<float>("Juro")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("juro")
                        .HasColumnType("float")
                        .HasDefaultValue(0f);

                    b.Property<float>("Multa")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("multa")
                        .HasColumnType("float")
                        .HasDefaultValue(0f);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("nome")
                        .HasColumnType("varchar(200)");

                    b.Property<int>("QtdDiasAtraso")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("qtd_dias_atraso")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal>("ValorCorrigido")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("valor_corrigido")
                        .HasColumnType("decimal(13,9)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("ValorOriginal")
                        .HasColumnName("valor_original")
                        .HasColumnType("decimal(13,2)");

                    b.HasKey("Id");

                    b.ToTable("conta_a_pagar");
                });
#pragma warning restore 612, 618
        }
    }
}
